<template>
  <div class="bg-[#f3f4ff] p-10 rounded-xl">
    <h1 class="text-3xl mb-5">Privacy Policy</h1>
    <p class="mb-5">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    <h2 class="font-bold">Arcu Bibendum</h2>
    <p class="mb-5">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Luctus venenatis lectus magna fringilla urna porttitor rhoncus dolor purus. Ornare aenean euismod elementum nisi quis eleifend quam adipiscing. Varius morbi enim nunc faucibus a pellentesque sit.</p>
    <h2 class="font-bold">Amet Venenatis</h2>
    <p class="mb-5">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pharetra diam sit amet nisl suscipit adipiscing bibendum est. Est lorem ipsum dolor sit. Sagittis nisl rhoncus mattis rhoncus urna neque viverra justo nec. Quis enim lobortis scelerisque fermentum dui faucibus in. Vehicula ipsum a arcu cursus vitae congue mauris. Eget mi proin sed libero. Condimentum mattis pellentesque id nibh tortor. Velit sed ullamcorper morbi tincidunt ornare. Diam maecenas ultricies mi eget mauris pharetra et ultrices.</p>
    <h2 class="font-bold">Eu Volutpat Odio</h2>
    <p class="mb-5">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nulla malesuada pellentesque elit eget gravida. Consequat id porta nibh venenatis cras. Nunc sed blandit libero volutpat sed cras ornare arcu. Sollicitudin nibh sit amet commodo. Ultricies lacus sed turpis tincidunt id aliquet risus feugiat. Et egestas quis ipsum suspendisse ultrices gravida dictum fusce ut. Non arcu risus quis varius quam quisque. Porttitor lacus luctus accumsan tortor posuere ac ut. Nunc pulvinar sapien et ligula ullamcorper malesuada. Ut placerat orci nulla pellentesque dignissim. Id nibh tortor id aliquet lectus proin. Est sit amet facilisis magna etiam tempor orci. Feugiat sed lectus vestibulum mattis ullamcorper.</p>
    <p>Neque volutpat ac tincidunt vitae. At quis risus sed vulputate. Imperdiet dui accumsan sit amet nulla. Id faucibus nisl tincidunt eget nullam. Magnis dis parturient montes nascetur. Diam phasellus vestibulum lorem sed risus ultricies tristique nulla. Magna ac placerat vestibulum lectus mauris ultrices. Ac turpis egestas integer eget aliquet nibh praesent tristique magna. Vestibulum lectus mauris ultrices eros in. Tempor orci eu lobortis elementum. Arcu felis bibendum ut tristique. Nunc mattis enim ut tellus elementum sagittis. Risus quis varius quam quisque id diam vel. Volutpat sed cras ornare arcu dui vivamus. Velit ut tortor pretium viverra suspendisse potenti nullam ac. Molestie nunc non blandit massa enim nec dui. Lectus urna duis convallis convallis tellus id.</p>
    <p class="mb-5">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Luctus venenatis lectus magna fringilla urna porttitor rhoncus dolor purus. Ornare aenean euismod elementum nisi quis eleifend quam adipiscing. Varius morbi enim nunc faucibus a pellentesque sit.</p>
    <h2 class="font-bold">Amet Venenatis</h2>
    <p class="mb-5">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pharetra diam sit amet nisl suscipit adipiscing bibendum est. Est lorem ipsum dolor sit. Sagittis nisl rhoncus mattis rhoncus urna neque viverra justo nec. Quis enim lobortis scelerisque fermentum dui faucibus in. Vehicula ipsum a arcu cursus vitae congue mauris. Eget mi proin sed libero. Condimentum mattis pellentesque id nibh tortor. Velit sed ullamcorper morbi tincidunt ornare. Diam maecenas ultricies mi eget mauris pharetra et ultrices.</p>
    <h2 class="font-bold">Eu Volutpat Odio</h2>
    <p class="mb-5">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nulla malesuada pellentesque elit eget gravida. Consequat id porta nibh venenatis cras. Nunc sed blandit libero volutpat sed cras ornare arcu. Sollicitudin nibh sit amet commodo. Ultricies lacus sed turpis tincidunt id aliquet risus feugiat. Et egestas quis ipsum suspendisse ultrices gravida dictum fusce ut. Non arcu risus quis varius quam quisque. Porttitor lacus luctus accumsan tortor posuere ac ut. Nunc pulvinar sapien et ligula ullamcorper malesuada. Ut placerat orci nulla pellentesque dignissim. Id nibh tortor id aliquet lectus proin. Est sit amet facilisis magna etiam tempor orci. Feugiat sed lectus vestibulum mattis ullamcorper.</p>
    <p>Neque volutpat ac tincidunt vitae. At quis risus sed vulputate. Imperdiet dui accumsan sit amet nulla. Id faucibus nisl tincidunt eget nullam. Magnis dis parturient montes nascetur. Diam phasellus vestibulum lorem sed risus ultricies tristique nulla. Magna ac placerat vestibulum lectus mauris ultrices. Ac turpis egestas integer eget aliquet nibh praesent tristique magna. Vestibulum lectus mauris ultrices eros in. Tempor orci eu lobortis elementum. Arcu felis bibendum ut tristique. Nunc mattis enim ut tellus elementum sagittis. Risus quis varius quam quisque id diam vel. Volutpat sed cras ornare arcu dui vivamus. Velit ut tortor pretium viverra suspendisse potenti nullam ac. Molestie nunc non blandit massa enim nec dui. Lectus urna duis convallis convallis tellus id.</p>
    <p class="mb-5">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Luctus venenatis lectus magna fringilla urna porttitor rhoncus dolor purus. Ornare aenean euismod elementum nisi quis eleifend quam adipiscing. Varius morbi enim nunc faucibus a pellentesque sit.</p>
    <h2 class="font-bold">Amet Venenatis</h2>
    <p class="mb-5">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pharetra diam sit amet nisl suscipit adipiscing bibendum est. Est lorem ipsum dolor sit. Sagittis nisl rhoncus mattis rhoncus urna neque viverra justo nec. Quis enim lobortis scelerisque fermentum dui faucibus in. Vehicula ipsum a arcu cursus vitae congue mauris. Eget mi proin sed libero. Condimentum mattis pellentesque id nibh tortor. Velit sed ullamcorper morbi tincidunt ornare. Diam maecenas ultricies mi eget mauris pharetra et ultrices.</p>
    <h2 class="font-bold">Eu Volutpat Odio</h2>
    <p class="mb-5">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nulla malesuada pellentesque elit eget gravida. Consequat id porta nibh venenatis cras. Nunc sed blandit libero volutpat sed cras ornare arcu. Sollicitudin nibh sit amet commodo. Ultricies lacus sed turpis tincidunt id aliquet risus feugiat. Et egestas quis ipsum suspendisse ultrices gravida dictum fusce ut. Non arcu risus quis varius quam quisque. Porttitor lacus luctus accumsan tortor posuere ac ut. Nunc pulvinar sapien et ligula ullamcorper malesuada. Ut placerat orci nulla pellentesque dignissim. Id nibh tortor id aliquet lectus proin. Est sit amet facilisis magna etiam tempor orci. Feugiat sed lectus vestibulum mattis ullamcorper.</p>
    <p>Neque volutpat ac tincidunt vitae. At quis risus sed vulputate. Imperdiet dui accumsan sit amet nulla. Id faucibus nisl tincidunt eget nullam. Magnis dis parturient montes nascetur. Diam phasellus vestibulum lorem sed risus ultricies tristique nulla. Magna ac placerat vestibulum lectus mauris ultrices. Ac turpis egestas integer eget aliquet nibh praesent tristique magna. Vestibulum lectus mauris ultrices eros in. Tempor orci eu lobortis elementum. Arcu felis bibendum ut tristique. Nunc mattis enim ut tellus elementum sagittis. Risus quis varius quam quisque id diam vel. Volutpat sed cras ornare arcu dui vivamus. Velit ut tortor pretium viverra suspendisse potenti nullam ac. Molestie nunc non blandit massa enim nec dui. Lectus urna duis convallis convallis tellus id.</p>
 </div>
</template>